[Feat]: Issue #14 - Add Verdana Base Font Family
s-katte/React-Code-Pen pull request #37
Opened 2020-10-21 02:54 UTC by mcastre

## Link to the Issue

Resolves [Issue #14 ](https://github.com/s-katte/Sketchify/issues/14)

## Description of your PR

Set the base font family of the application to Verdana in index.css.

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/5702024/96667293-6dfa5100-131e-11eb-8d67-f11a210e5ce7.png)

## Test Plan

Can delete line 6 in index.css to see app revert to the original font for comparison.

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes.

2020-10-21 04:39 UTC, t0xic0der requested changes
I have requested some changes. Please follow through.

2020-10-21 04:39 UTC, t0xic0der commented on src/index.css
> +    font-family: 'Verdana', sans-serif;
Please use Inter (https://fonts.google.com/specimen/Inter) and not Verdana

2020-10-21 06:04 UTC, s-katte requested changes
@mcastre, please do the changes suggested by @t0xic0der.

2020-10-21 18:29 UTC, mcastre commented
@t0xic0der @s-katte PR has been updated with requested changes

2020-10-21 18:34 UTC, mcastre commented
Sorry, forgot to update from master. Excuse the extra commits.

2020-10-22 00:43 UTC, s-katte approved these changes
Looks fine to me.
Merging it.

2020-10-22 00:43 UTC, merged